var feedback_od = false;
var feedback_os = false;
var feedback_cyl = false;
var feedback_sph = false;
var lens =''; //this is lens type
var plano_od=false;
var plano_os=false;
var overall_message='<b>You have following errors. Please show your patience to fill the prescription.</b>';
var upload_success=false;
var test='';
var power_os=0
var power_od=0;
var promocode=false;
var total_price=0;
var free_category=0;
var current_category=0;
var greater_cyl=0;
var active_lens_packages = new Array();